[workspace]
members = [
	"kernel_main",
	"kernel_bootloader",
	"kernel_allocator",
	"kernel_executor",
	"kernel_sbi",
	"kernel_paging",
	"kernel_printer",
	"kernel_send_generic",
	"kernel_syscall",
	"kernel_resource_map",
	"kernel_services",
	"kernel_process",
	"kernel_api"
]